name: Bump Homebrew Formula

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to bump (e.g., v0.1.0). Leave empty to use the release tag."
        required: false
        type: string
      dry_run:
        description: "If true, open a PR with a -dryrun suffix for safe testing."
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

permissions:
  contents: read
  pull-requests: write

jobs:
  bump:
    runs-on: macos-latest
    env:
      # ---- Customize these if your tap or formula path differ ----
      TAP_OWNER: ${{ vars.TAP_OWNER || 'ryanwjackson' }}
      TAP_REPO:  ${{ vars.TAP_REPO  || 'homebrew-tap' }}
      FORMULA_PATH: ${{ vars.FORMULA_PATH || 'Formula/gtr.rb' }}
      # ------------------------------------------------------------
    steps:
      - name: Checkout (handy if you later read files)
        uses: actions/checkout@v4

      - name: Ensure GH CLI is authenticated
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_BUMP_TOKEN }}
        run: gh auth status

      - name: Compute tarball URL and SHA256
        id: meta
        shell: bash
        run: |
          set -euo pipefail
          # Prefer manual input on workflow_dispatch; else use the tag from the release ref
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.tag }}" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="${GITHUB_REF_NAME}"
          fi
          REPO="${{ github.repository }}"  # should be ryanwjackson/gtr
          TARBALL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
          echo "Tarball: $TARBALL"

          curl -L "$TARBALL" -o source.tar.gz
          SHA256="$(shasum -a 256 source.tar.gz | awk '{print $1}')"

          echo "tag=$TAG"         >> "$GITHUB_OUTPUT"
          echo "tarball=$TARBALL" >> "$GITHUB_OUTPUT"
          echo "sha256=$SHA256"   >> "$GITHUB_OUTPUT"

      - name: Clone tap and bump formula
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_BUMP_TOKEN }}
        shell: bash
        run: |
          set -euo pipefail
          gh repo clone "$TAP_OWNER/$TAP_REPO" tap
          cd tap

          # Determine dry-run suffix and branch name
          DRY="${{ github.event.inputs.dry_run || 'false' }}"
          SUFFIX=""
          if [[ "$DRY" == "true" ]]; then SUFFIX="-dryrun"; fi
          BRANCH="bump-gtr-${{ steps.meta.outputs.tag }}$SUFFIX"
          git checkout -b "$BRANCH"

          # Configure git identity (can also set via repo variables)
          git config user.name  "${{ vars.GIT_USER_NAME  || 'github-actions[bot]' }}"
          git config user.email "${{ vars.GIT_USER_EMAIL || '41898282+github-actions[bot]@users.noreply.github.com' }}"

          # In-place edit with Perl (portable across BSD/GNU)
          perl -0777 -pe 's|^  url ".*"|  url "'${{ steps.meta.outputs.tarball }}'"|m; s|^  sha256 ".*"|  sha256 "'${{ steps.meta.outputs.sha256 }}'"|m' -i "$FORMULA_PATH"

          echo "Diff:"
          git --no-pager diff -- "$FORMULA_PATH" || true

          git add "$FORMULA_PATH"
          git commit -m "gtr: bump to ${{ steps.meta.outputs.tag }}$SUFFIX"
          git push -u origin "$BRANCH"

          # Open a PR targeting the tap's default branch
          gh pr create \
            --title "Bump gtr to ${{ steps.meta.outputs.tag }}$SUFFIX" \
            --body  "Automated bump (dry_run=${DRY}): update URL and SHA256 for ${{ steps.meta.outputs.tag }}." \
            --fill

      # Optional: uncomment to lint the formula in CI for extra safety
      # - name: Brew audit (optional)
      #   shell: bash
      #   run: |
      #     set -euo pipefail
      #     brew update
      #     brew audit --strict --new-formula "tap/$FORMULA_PATH"