name: Continuous Integration

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        git config --global user.name "CI Test"
        git config --global user.email "ci@test.local"

    - name: Setup Scripts
      run: |
        # Set proper executable permissions
        chmod +x bin/gtr bin/pr test/test-runner.sh test/*.sh
        # Verify permissions were set correctly
        echo "Verifying script permissions..."
        ls -la bin/gtr bin/pr test/test-runner.sh
        echo "Script permissions set successfully"

    - name: Run Tests
      run: ./test/test-runner.sh

    - name: Verify Script Works
      run: |
        echo "Testing modular script..."
        ./bin/gtr --version
        echo "Script functional ✓"

  lint:
    name: Shell Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Lint Shell Scripts
      run: |
        echo "Linting main scripts..."
        shellcheck bin/gtr || true
        echo "Linting library modules..."
        shellcheck lib/*.sh || true
        echo "Linting test scripts..."
        shellcheck test/*.sh test-helpers/*.sh || true
        echo "Note: Some warnings are expected due to dynamic sourcing"